server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
spring:
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://localhost:3306/yupao
    url: jdbc:mysql://localhost:3306/yupaotest
#  Session失效时间，设置为30分钟
  session:
    timeout: 1800
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
#  redis配置
  redis:
    port: 6379
    host: localhost
    database: 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

